# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u5-iJbyrd5MZd38jsSlJwx8KXx58UY3I
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd /content/drive/MyDrive/Soft Computing/

import tensorflow as tf
model = tf.keras.models.load_model('my_model.hdf5')

!pip install streamlit
import streamlit as st
st.header("Age and Gender Detection")
st.write("This is an web app to predict age and gender from a human image.")
file = st.file_uploader("Please upload an image file", type=["jpg", "png"])

from PIL import Image, ImageOps
import numpy as np
def import_and_predict(photo, model):
        photo = photo.resize((128,128))
        photo = photo.convert(mode='L')
        photo = np.asarray(photo)
        photo = photo.reshape(128,128,1)
        photo = photo/255.0

        pred = model.predict(photo.reshape(1, 128, 128, 1))
        
        gender_dict = {0:'Male', 1:'Female'}
        pred_gender = gender_dict[round(pred[0][0][0])]
        pred_age = round(pred[1][0][0])
        st.write("Predicted Gender:", pred_gender, "Predicted Age:", pred_age)
        
if file is None:
    st.text("Please upload an image file")
else:
    image = Image.open(file)
    st.image(image, use_column_width=True)
    import_and_predict(image, model)